### ISSUE TITLE
What is the status of the new website

### ISSUE THREAD

**Issue by TheItachiUchiha** [javafx-maven-plugin/javafx-maven-plugin.github.io#1]
It has been a long time that zenjava website was taken down and almost 2 months since this repository was created, but there has not been any updates since then. Will this repository contain the website for the plugin or is this repository dead?

**Comment by FibreFoX** [comment]
Will be released this month

**Comment by FibreFoX** [comment]
The new website is available now, but still "beta". Will be improved as well, but I hope this will help a bit.
